apiVersion: v1
kind: Pod
metadata:
  labels:
    app: test
  name: pod-volume-test
  namespace: default
spec:
  containers:
  - name: test
    image: busybox
    command: ["/bin/sh","-c","sleep 12h"]
    volumeMounts:
    - name: log
      mountPath: /data
  - name: web
    image: nginx
    volumeMounts:
    - name: log
      mountPath: /usr/share/nginx/html
  volumes:
  - name: log
    emptyDir: {}