apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: example-web-app
  annotations:
    kubernetes.io/ingress.class: "traefik"
spec:
  rules:
  - host: test1.haimaxy.com
    http:
      paths:
      - path: /
        backend:
          serviceName: svc
          servicePort: 8080
  - host: test2.haimaxy.com
    http:
      paths:
      - path: /svc
        backend:
          serviceName: svc
          servicePort: 8080
  - host: test3.haimaxy.com
    http:
      paths:
      - path: /svc
        backend:
          serviceName: svc
          servicePort: 8080