apiVersion: v1
kind: PersistentVolume
metadata:
  name: nginx-pv
  labels:
    name: nginx-pv
    release: stable
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Recycle
  hostPath:
    path: /test-volume
  