apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nginx-pvc 
  namespace: default
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  selector:
    matchLabels:
      name: nginx-pv 
      release: stable